name: UltimateItem
version: '${project.version}'
main: fr.rammex.ultimateitem.UltimateItem
depend:
  - ShopGUIPlus
  - Factions
  - ProtocolLib
commands:
  ultimateitem:
    description: Commande principale du plugin UltimateItem
  itemcraft:
    description: Commande pour créer un item
