name: ArkaItems
version: '${project.version}'
main: fr.rammex.arkaitems.ArkaItems
depend:
  - ShopGUIPlus
  - Factions
  - ProtocolLib
commands:
  arkaitem:
    description: Commande principale du plugin ArkaItems
  itemcraft:
    description: Commande pour créer un item
