name: ArkaItems
version: '${project.version}'
main: fr.rammex.arkaitems.ArkaItems
depend:
  - ShopGUIPlus
softdepend:
  - WorlGuard
  - Factions
commands:
  arkaitems:
    description: Commande principale du plugin ArkaItems
